name: Build macOS .app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build .app
        env:
          PYTHONPATH: src
        run: python setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Verificador_SAFT_AO.app
          path: 'dist/Verificador SAFT-AO.app'
